theme = "new_moon_rock"

[editor]
#auto-completion = true
#line-number = "relative"
auto-completion = true
auto-format = true
bufferline = "always"
color-modes = true
completion-replace = true
cursorcolumn = false
cursorline = false
default-line-ending = "lf"
end-of-line-diagnostics = "hint"
mouse = true
popup-border = "all"
rulers = [79, 99]
true-color = true

[editor.auto-save]
focus-lost = true

[editor.cursor-shape]
insert = "block"

[editor.file-picker]
hidden = false
ignore = false
git-ignore = true
git-global = false

[editor.gutters]
line-numbers.min-width = 2

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 0

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.lsp]
display-inlay-hints = true
display-messages = true
display-progress-messages = true
goto-reference-include-declaration = false

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 40
#wrap-indicator = ""  # set wrap-indicator to "" to hide it

[editor.statusline]
left = ["mode","spinner","file-name","read-only-indicator",
  "file-modification-indicator","separator","version-control"]
right = ["diagnostics", "separator", "selections", "register", "position", "file-encoding"]
separator = "╎"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.whitespace.render]
space = "none"
nbsp = "none"
tab = "none"
newline = "none"

[keys.normal]
#C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
#C-o = ":open ~/.config/helix/config.toml"
#C-l = ":open ~/.config/helix/languages.toml"
# esc is remapped to capslock locally
# esc = ["collapse_selection", "keep_primary_selection", ":w"]
# C-v = "vsplit"
# C-h = "jump_view_left"
# C-j = "jump_view_down"
# C-k = "jump_view_up"
# C-l = "jump_view_right"
# "C-," = "goto_previous_buffer"
# "C-." = "goto_next_buffer"
# "K" = "insert_newline"
# Move line up/down using A-k, A-j
# "A-k" = [
#   "extend_to_line_bounds",
#   "delete_selection",
#   "move_line_up",
#   "paste_before"
# ]
# "A-j" = [
#   "extend_to_line_bounds",
#   "delete_selection",
#   "move_line_down",
#   "paste_before"
# ]

#[keys.normal.":"]
#x = "write-buffer-close"
 
[keys.normal.g]
q = ":bc"
# Q = ":bc!"

# Remove vscode "training wheels"
# Comment this to enable arrow navigation in insert mode
# [keys.insert]
# j = { j = "normal_mode" }
# "C-space" = "completion"
# A-b = ["move_prev_word_start", "collapse_selection"]
# A-f = ["move_next_word_end", "move_char_right"]
# C-a = "goto_first_nonwhitespace"
# C-b = "move_char_left"
# C-d = "delete_char_forward"
# C-e = "goto_line_end_newline"
# C-f = "move_char_right"
# C-n = "move_line_down"
# C-p = "move_line_up"


# Config Mode
# [keys.normal."C-backspace"]
# r = [":config-reload", ":reload-all"]
# o = ":config-open"
# l = ":o ~/.config/helix/languages.toml"
# C-g = [":new", ":insert-output lazygit", ":buffer-close", ":redraw"]
